name: patapata_builder
version: 1.0.0
description: This package is a plugin for Patapata that uses build_runner to generate classes used in Patapata app.
homepage: https://github.com/gree/patapata
repository: https://github.com/gree/patapata/tree/main/packages/patapata_builder

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  patapata_core: ^1.2.0

  meta: ^1.15.0
  analyzer: '^6.7.0'
  build: ^2.0.0
  build_config: '^1.1.1'
  source_gen: '^1.5.0'

dev_dependencies:
  build_runner: ^2.4.13
  dart_flutter_team_lints: ^1.0.0
