name: patapata_firebase_messaging
description: This package is a plugin for Patapata that adds support for Firebase Cloud Messaging to your Patapata app.
version: 1.3.0
homepage: https://github.com/gree/patapata
repository: https://github.com/gree/patapata/tree/main/packages/patapata_firebase_messaging

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  patapata_core: ^1.3.0

  patapata_firebase_core: ^1.3.0

  firebase_messaging: ^15.2.4
  path_provider: ">=2.0.9 <3.0.0"
  crypto: ">=3.0.3 <4.0.0"
  flutter_local_notifications: ^19.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  plugin:
    platforms:
      android:
        package: dev.patapata.patapata_firebase_messaging
        pluginClass: PatapataFirebaseMessagingPlugin
