// Copyright (c) GREE, Inc.
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.

import 'package:patapata_core/patapata_core.dart';
import 'package:patapata_core/patapata_core_libs.dart';

import '../src/errors.dart';

/// This is the exception class that occurs in this sample application.
/// Exceptions generated by an app using Patapata should inherit from [PatapataException].
/// Please override the necessary members as specified.
base class ExampleException extends AppException {
  ExampleException({
    super.app,
    super.message,
    super.original,
    super.fingerprint,
    super.localeTitleData,
    super.localeMessageData,
    super.localeFixData,
    super.fix,
    super.logLevel,
    super.userLogLevel,
    super.overridableLocalization,
  });

  @override
  String get internalCode => '000';
}

/// This is the exception class for network-related issues that occur in this sample application.
base class ExampleNetworkException extends ExampleException {
  final int statusCode;

  ExampleNetworkException({
    required this.statusCode,
    super.fix,
    super.logLevel,
    super.userLogLevel,
  });

  @override
  String get defaultPrefix => 'APN';

  @override
  String get internalCode => '$statusCode';

  @override
  String get namespace => 'app.network';
}

/// This is the exception class for maintenance-related issues that occur in this sample application.
final class ExampleMaintenanceException extends ExampleNetworkException {
  ExampleMaintenanceException({
    required super.fix,
  }) : super(
          statusCode: 503,
          userLogLevel: Level.SHOUT,
        );
}
